### ISSUE TITLE
Maybe allow ipc-channel to build using rust stable on windows

### ISSUE THREAD

**Issue by staktrace** [servo/ipc-channel#118]
Right now if I try to build ipc-channel using stable rust (1.12.1 d4f39402a 2016-10-19) on windows, it fails with this error:

```
error[E0554]: #[feature] may not be used on the stable release channel
  --> C:\Users\kats\zspace\mozilla-git\third_party\rust\ipc-channel\src\lib.rs:11:4
   |
11 |                   feature(mpsc_select))]
   |                   ^^^^^^^^^^^^^^^^^^^^^
```

I'm not entirely sure what mpsc_select is, because that token doesn't appear anywhere else in the repo. Can this be removed, or can be rewritten using stuff that compiles with stable rust?

/cc @Ms2ger (who originally added the line in f4fef7d8b0)
/cc @jrmuizel as FYI

**Comment by emilio** [comment]
That's mainly #108, I guess.

**Comment by antrik** [comment]
After pondering this for a while, I tend to agree with @emilio : for practical purposes, the solution to this issue is probably in making sure all platforms get a "real" inter-process implementation. The `inprocess` back-end is really just a partial work-around; and we can't count on `mpsc_select()` getting stabilised in the foreseeable future (see https://github.com/rust-lang/rust/issues/27800 ) -- nor is there enough incentive for a major rewrite to avoid this dependency...

**Comment by Xaeroxe** [comment]
This now compiles on Rust stable for Windows. It should probably be closed.

**Comment by staktrace** [comment]
Thanks! Closing. (I didn't verify myself, and don't need this anymore myself either)
